services:
  - name: client
    buildCommand: npm run build
    startCommand: npm run start
    env:
      - key: NODE_ENV
        value: production

  - name: server
    buildCommand: echo "no build required"
    startCommand: node main.js
    env: 
      - key: NODE_ENV
        value: production